# Generated by Django 6.0.4 on 2026-04-16 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='skills.skill'),
        ),
    ]
