# Generated by Django 6.0.4 on 2026-04-25 20:07

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TutorEmbedding",
            fields=[
                (
                    "tutor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="embedding",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("embedding", pgvector.django.vector.VectorField(dimensions=384)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tutor_embeddings",
            },
        ),
    ]
