# Generated by Django 6.0.4 on 2026-04-16 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualification_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qualification',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['name'], name='idx_skills_name'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['category'], name='idx_skills_category'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.skill'),
        ),
        migrations.AddField(
            model_name='userskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.skill'),
        ),
        migrations.AddField(
            model_name='userskill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='qualification',
            index=models.Index(fields=['tutor'], name='idx_qualifications_tutor'),
        ),
        migrations.AddIndex(
            model_name='qualification',
            index=models.Index(fields=['skill'], name='idx_qualifications_skill'),
        ),
        migrations.AddIndex(
            model_name='qualification',
            index=models.Index(fields=['status'], name='idx_qualifications_status'),
        ),
        migrations.AddConstraint(
            model_name='qualification',
            constraint=models.CheckConstraint(condition=models.Q(('file_size__lte', 5242880)), name='chk_qualifications_file_size_max_5mb'),
        ),
        migrations.AddIndex(
            model_name='userskill',
            index=models.Index(fields=['user'], name='idx_user_skills_user'),
        ),
        migrations.AddIndex(
            model_name='userskill',
            index=models.Index(fields=['skill'], name='idx_user_skills_skill'),
        ),
        migrations.AddIndex(
            model_name='userskill',
            index=models.Index(fields=['skill_type'], name='idx_user_skills_type'),
        ),
        migrations.AddConstraint(
            model_name='userskill',
            constraint=models.UniqueConstraint(fields=('user', 'skill'), name='ux_user_skill_user_skill'),
        ),
    ]
